CFLAGS=-std=c99

all: WiltCompress WiltDecompress WiltCompress16 WiltDecompress16

WiltCompress: WiltCompress.c
	$(CC) $(CFLAGS) -o $@ $<

WiltDecompress: WiltDecompress.c
	$(CC) $(CFLAGS) -o $@ $<

WiltCompress16: WiltCompress16.c
	$(CC) $(CFLAGS) -o $@ $<

WiltDecompress16: WiltDecompress16.c
	$(CC) $(CFLAGS) -o $@ $<
